// Builds the offline demo (/demo/) from the live page template:
//   node demo/build.js
// Writes demo/index.html (the real app, rendered with the sample vendors in
// demo/snapshot.json and wired to demo/demo-db.js instead of Supabase) and
// demo/sw.js (caches everything the demo needs so it works with no internet).
// Re-run after changing app.html, js/, assets/ or the snapshot.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
process.env.VERCEL_GIT_COMMIT_SHA = 'demo';
const { render } = require(path.join(ROOT, 'api', 'render.js'));
const data = JSON.parse(fs.readFileSync(path.join(__dirname, 'snapshot.json'), 'utf8'));

let html = render(data, '/', {}).html;
const swap = (re, to, label) => {
  if (!(typeof re === 'string' ? html.includes(re) : html.match(re))) throw new Error('demo build: could not find ' + label);
  html = html.replace(re, to);
};
swap(/<!-- Google tag[\s\S]*?<\/script>\s*<script>[\s\S]*?gtag\('config'[^<]*<\/script>|<script async src="https:\/\/www\.googletagmanager\.com[\s\S]*?gtag\('config'[^<]*<\/script>/, '', 'analytics');
swap(/\?v=demo"/g, '"', 'script versions');
swap(/<script src="\/js\/vendor\/supabase\.js"><\/script>\s*/, '', 'supabase script');
swap(/<script src="\/js\/eventory-data\.js"><\/script>/, '<script src="/demo/demo-db.js"></script>', 'data layer');
swap(/<link rel="preconnect"[^>]*supabase[^>]*>\s*/, '', 'preconnect');
swap(/<meta name="robots" content="[^"]*">/, '<meta name="robots" content="noindex,nofollow">', 'robots');
html = html.replace(/<link rel="canonical"[^>]*>\s*/, '').replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>\s*/g, '');
swap(/<title>[^<]*<\/title>/, '<title>Eventory Demo</title>', 'title');
swap('<meta name="viewport" content="width=device-width, initial-scale=1">',
  '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n' +
  '<script>window.__EV_DEMO = true;</script>\n' +
  '<link rel="manifest" href="/demo/manifest.json">\n<meta name="theme-color" content="#FAFAF7">\n' +
  '<meta name="apple-mobile-web-app-capable" content="yes">\n<meta name="mobile-web-app-capable" content="yes">\n' +
  '<meta name="apple-mobile-web-app-title" content="Eventory">\n<link rel="apple-touch-icon" href="/demo/icon-180.png">', 'viewport');
swap(/<\/body>/, '<script src="/demo/demo-guide.js"></script>\n' +
  '<script>if ("serviceWorker" in navigator) navigator.serviceWorker.register("/demo/sw.js", { scope: "/demo/" });</script>\n</body>', 'body end');
if (/supabase\.co|googletagmanager|src="\/js\/eventory-data\.js/.test(html.replace(/<div id="ev-ssr">[\s\S]*?<\/div>\n/, ''))) {
  throw new Error('demo build: online dependency left in index.html: ' + html.match(/.{0,80}(supabase\.co|googletagmanager|src="\/js\/eventory-data\.js).{0,60}/)[0]);
}
fs.writeFileSync(path.join(__dirname, 'index.html'), html);

// Everything the demo loads, for the offline cache.
const walk = (dir) => fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true }).flatMap((e) =>
  e.isDirectory() ? walk(dir + '/' + e.name) : [dir + '/' + e.name]);
const files = [
  'demo/index.html', 'demo/demo-db.js', 'demo/demo-guide.js', 'demo/manifest.json',
  'demo/icon-180.png', 'demo/icon-192.png', 'demo/icon-512.png',
  'js/seo-core.js', 'js/dc-runtime.js', 'js/eventory-ds.js', 'js/vendor/react.production.min.js', 'js/vendor/react-dom.production.min.js',
  'VendorTile2.dc.html', ...walk('assets'),
];
const hash = crypto.createHash('sha256');
for (const f of files) hash.update(f).update(fs.readFileSync(path.join(ROOT, f)));
const version = hash.digest('hex').slice(0, 12);
const urls = ['/demo/', ...files.filter((f) => f !== 'demo/index.html').map((f) => '/' + f)];
const sw = `// Generated by demo/build.js. Caches the whole demo so it runs offline.
const CACHE = 'eventory-demo-${version}';
const FILES = ${JSON.stringify(urls, null, 1)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES.map((u) => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith('eventory-demo-') && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  // Any page under /demo/ is the demo itself.
  const key = url.pathname.startsWith('/demo/') && !/\\.[a-z0-9]+$/i.test(url.pathname) ? '/demo/' : url.pathname;
  e.respondWith(caches.open(CACHE).then((c) => c.match(key, { ignoreSearch: true }).then((hit) => hit || fetch(req).catch(() => c.match('/demo/')))));
});
`;
fs.writeFileSync(path.join(__dirname, 'sw.js'), sw);
console.log('demo built: version', version, '-', urls.length, 'files cached,',
  Math.round(files.reduce((n, f) => n + fs.statSync(path.join(ROOT, f)).size, 0) / 1024) + ' KB');
