// Generated by demo/build.js. Caches the whole demo so it runs offline.
const CACHE = 'eventory-demo-fc106925236a';
const FILES = [
 "/demo/",
 "/demo/demo-db.js",
 "/demo/demo-guide.js",
 "/demo/manifest.json",
 "/demo/icon-180.png",
 "/demo/icon-192.png",
 "/demo/icon-512.png",
 "/js/seo-core.js",
 "/js/dc-runtime.js",
 "/js/eventory-ds.js",
 "/js/vendor/react.production.min.js",
 "/js/vendor/react-dom.production.min.js",
 "/VendorTile2.dc.html",
 "/assets/categories/catering.jpg",
 "/assets/categories/entertainment.jpg",
 "/assets/categories/photography.jpg",
 "/assets/categories/production.jpg",
 "/assets/categories/rentals.jpg",
 "/assets/categories/venues.jpg",
 "/assets/fonts/0bb776ff.woff2",
 "/assets/fonts/140ba510.woff2",
 "/assets/fonts/19b73b93.woff2",
 "/assets/fonts/24d14c63.woff2",
 "/assets/fonts/58258b3c.woff2",
 "/assets/fonts/70cc687c.woff2",
 "/assets/fonts/759b4226.woff2",
 "/assets/fonts/7b34f9a4.woff2",
 "/assets/fonts/84ce0b8a.woff2",
 "/assets/fonts/8c39d970.woff2",
 "/assets/fonts/97066a5c.woff2",
 "/assets/fonts/9706cca7.woff2",
 "/assets/fonts/9e306047.woff2",
 "/assets/fonts/a681334a.woff2",
 "/assets/fonts/a7a79df4.woff2",
 "/assets/fonts/ab51c78f.woff2",
 "/assets/fonts/ad8360f9.woff2",
 "/assets/fonts/bb1a9493.woff2",
 "/assets/fonts/cdfd78a5.woff2",
 "/assets/fonts/f72ce2ea.woff2",
 "/assets/fonts/f966a942.woff2",
 "/assets/hero/bar.jpg",
 "/assets/hero/catering.jpg",
 "/assets/hero/decor.jpg",
 "/assets/hero/makeup.jpg",
 "/assets/hero/photobooth.jpg",
 "/assets/hero/stage-decor.jpg",
 "/assets/hero/stage.jpg",
 "/assets/hero/venue.jpg",
 "/assets/hero/videography.jpg",
 "/assets/hero-photo.jpg"
];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES.map((u) => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith('eventory-demo-') && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  // Any page under /demo/ is the demo itself.
  const key = url.pathname.startsWith('/demo/') && !/\.[a-z0-9]+$/i.test(url.pathname) ? '/demo/' : url.pathname;
  e.respondWith(caches.open(CACHE).then((c) => c.match(key, { ignoreSearch: true }).then((hit) => hit || fetch(req).catch(() => c.match('/demo/')))));
});
