-- Categories, event types and blog posts the site ships with.
-- (The same migration in the database also carried over the old project's
-- vendors and packages; those rows hold contact details, so they are not in git.)
insert into public.categories values ('photography','Photography','assets/categories/photography.jpg',0);
insert into public.categories values ('videography','Videography','assets/categories/production.jpg',1);
insert into public.categories values ('catering','Catering','assets/categories/catering.jpg',2);
insert into public.categories values ('decor','Decor',null,3);
insert into public.categories values ('venues','Venues','assets/categories/venues.jpg',4);
insert into public.categories values ('entertainment','DJs and Entertainment','assets/categories/entertainment.jpg',5);
insert into public.categories values ('cakes','Cakes',null,6);
insert into public.categories values ('florals','Florals',null,7);
insert into public.categories values ('rentals','Rentals','assets/categories/rentals.jpg',8);
insert into public.categories values ('makeup','Makeup and Hair',null,9);
insert into public.categories values ('planning','Event Planning',null,10);
insert into public.categories values ('bar','Bar Services',null,11);
insert into public.event_types values ('weddings','Weddings','Weddings',array['venues','photography','catering','decor','florals','cakes','makeup','entertainment','bar']::text[],0);
insert into public.event_types values ('birthdays','Birthdays','Birthdays',array['venues','catering','cakes','decor','entertainment','rentals']::text[],1);
insert into public.event_types values ('corporate','Corporate Events','Corporate',array['venues','catering','videography','entertainment','bar','planning']::text[],2);
insert into public.event_types values ('christenings','Christenings','Christenings',array['catering','cakes','decor','photography']::text[],3);
insert into public.event_types values ('sports','5Ks and Sports Events','5Ks',array['rentals','entertainment','photography','videography','catering']::text[],4);
insert into public.event_types values ('launches','Product Launches','Product Launches',array['venues','videography','photography','bar','decor','planning']::text[],5);
insert into public.event_types values ('family','Family Days','Family Days',array['rentals','catering','entertainment','decor']::text[],6);
insert into public.event_types values ('religious','Religious Events','Religious',array['venues','catering','decor','florals']::text[],7);
insert into public.event_types values ('other','Other Events','Other',array['venues','catering','entertainment','rentals']::text[],8);
insert into public.blog_posts (id,tag,published_on,read_label,img_path,title,excerpt,body,vendor_slugs) values ('wedding-first','Planning guide','2026-09-18','5 MIN READ','assets/hero/venue.jpg','What to book first for a Trinidad wedding','Venue, photographer and caterer go early. Most other vendors can wait until you have a date.',array['Popular venues in Chaguaramas and Port of Spain are often booked a year out for December and Carnival-adjacent weekends. Lock the venue first, because your date depends on it.','Photographers and caterers come next. Both usually take a limited number of events per weekend, and the good ones fill quickly in peak season.','Decor, florals, cakes and makeup can usually be booked three to six months out. Send those inquiries once your venue and colour palette are settled.']::text[],'{}'::text[]);
insert into public.blog_posts (id,tag,published_on,read_label,img_path,title,excerpt,body,vendor_slugs) values ('launch-pos','Corporate','2026-09-09','4 MIN READ','assets/hero/stage-decor.jpg','Planning a product launch in Port of Spain','A launch needs a room, a way to capture it, and something for guests to hold. Here is the short list.',array['Start with the room and the run of show. A planner or coordinator will save your team most of the back-and-forth with the other vendors.','Book video early if you need same-week social edits. Ask for vertical cuts in the brief so nobody has to reshoot.','A mobile bar with a signature drink gives guests something to talk about without taking over the programme.']::text[],'{}'::text[]);
insert into public.blog_posts (id,tag,published_on,read_label,img_path,title,excerpt,body,vendor_slugs) values ('per-head','Pricing','2026-08-28','3 MIN READ','assets/hero/catering.jpg','How caterers price per head','What is usually included in a per-head price, and what gets added on.',array['Most caterers quote a range per head based on the number of mains and sides. Staff, chafing dishes and cleanup are often included, but ask.','Plated service costs more than buffet because it needs more staff. Many caterers also set a minimum guest count for plated dinners.','Send your guest count and rough menu in the inquiry. Caterers can give a much tighter quote with those two numbers.']::text[],'{}'::text[]);
insert into public.blog_posts (id,tag,published_on,read_label,img_path,title,excerpt,body,vendor_slugs) values ('soundwave','Vendor spotlight','2026-08-15','3 MIN READ','assets/hero/photobooth.jpg','Vendor spotlight: Soundwave Sessions','An Arima DJ team that brings its own sound, lighting and MC.',array['Soundwave Sessions plays soca, dancehall, throwbacks and wedding sets, and handles everything from backyard birthdays to race-day start lines.','They bring their own sound and lighting, so you do not need a separate production vendor for most events under 300 guests.']::text[],array['soundwave-sessions']::text[]);
insert into public.blog_posts (id,tag,published_on,read_label,img_path,title,excerpt,body,vendor_slugs) values ('5k','Planning guide','2026-08-02','4 MIN READ','assets/hero/stage.jpg','What a 5K actually needs','Barriers, water stations, a PA and someone at the finish line with a camera.',array['The course is the easy part. Most of the work is at the start and finish: arches, barriers, timing mats and a PA the runners can hear.','Plan one water station per two kilometres, plus one at the finish. Rental companies can supply the stands, coolers and tents together.','Participants want photos. A photographer at the finish line with a shared gallery is one of the cheapest ways to get people talking about next year.']::text[],'{}'::text[]);
